rspack-contrib/storybook-rsbuild

README.md

docs: add banner image

---

packages/react-rsbuild/src/loaders/react-docgen-loader.ts

While in the previous code, `const tsconfigPath = await findUp('tsconfig.json', { cwd: process.cwd() })` introduced aysnc logic so the `tsconfigPathsInitialized` will not take effect when multiple `reactDocgenLoader` invoked at the same time and will result in repeated initialization for many times. 
this PR fixed that to work with the async logic.
---
Conceptually, this should also raise with `@storybook/builder-webpack5` but I can't reproduce it with a demo. The async logic will always be finished before other invoking. I will launch another a PR to `@storybookjs/storybook` since the code here is copied from the repository (https://github.com/storybookjs/storybook/blob/next/code/presets/react-webpack/src/loaders/react-docgen-loader.ts).
cc @chenjiahan

fix(react-rsbuild): avoid race condition in async

---

.github/workflows/release.yaml

The release workflow would be:
1. bump version locally with changeset and generate a commit
2. merge the commit to main branch
3. Trigger https://github.com/rspack-contrib/storybook-rsbuild/actions/workflows/release.yaml manually, git tag and GitHub release will be created then.
TODO: document this if the workflow is proven to work.

chore: tweak release workflow

---

README.md
packages/builder-rsbuild/package.json
packages/builder-rsbuild/src/preview/iframe-rsbuild.config.ts
packages/builder-rsbuild/src/types.ts
packages/react-rsbuild/src/types.ts
packages/vue3-rsbuild/src/types.ts
pnpm-lock.yaml
sandboxes/react-rsbuild/.storybook/main.ts

Port from https://www.npmjs.com/package/@storybook/builder-webpack5.

feat: support fork-ts-checker-webpack-plugin

---

packages/builder-rsbuild/src/loaders/export-order-loader.ts
packages/react-rsbuild/src/loaders/react-docgen-loader.ts

Related Counter PR at Storybook: https://github.com/storybookjs/storybook/pull/27171
Currently, the sourcemap generation for story files is broken. If rspack behaves like Webpack, then loaders have to chain sourcemaps. This doesn't happen automatically, as Vite/Rollup does. The issue is that the magic-string [doesn't support](https://github.com/Rich-Harris/magic-string/issues/226) sourcemap chaining currently.
The files I have touched only add content at the end of the file. Therefore, creating source maps is not essential since the line/column mapping will stay the same.
This fix only ensures that the source view with enabled sourcemaps in the browser isn't completely broken for `.stories.ts|js` files. The source map mapping still doesn't refer to the original file, but some compiled …

fix: sourcemap generation for story files

---

packages/builder-rsbuild/src/preview/virtual-module-mapping.ts

fix #15.
Should use unified POSIX path as Storybook for Windows.

fix: vitual module should compat with Windows

---

packages/builder-rsbuild/package.json
packages/builder-rsbuild/src/preview/iframe-rsbuild.config.ts
pnpm-lock.yaml

rsbuild-plugin-html-minifier-terser support options since 1.1.0.

fix: restore html minimize options

---

README.md
packages/builder-rsbuild/package.json
packages/builder-rsbuild/src/preview/iframe-rsbuild.config.ts
packages/builder-rsbuild/src/preview/virtual-module-mapping.ts
packages/builder-rsbuild/src/types.ts
packages/react-rsbuild/package.json
packages/vue3-rsbuild/package.json
pnpm-lock.yaml
sandboxes/react-16/.storybook/main.ts
sandboxes/react-16/package.json
sandboxes/react-18/package.json
sandboxes/vue3/package.json

Introduced in https://github.com/web-infra-dev/rspack/releases/tag/v0.7.1.

feat: support LazyCompilation

---

packages/builder-rsbuild/src/index.ts
packages/react-rsbuild/package.json

fix: make rsbuild listen on a random port

---

packages/builder-rsbuild/src/preview/iframe-rsbuild.config.ts

Fix https://github.com/rspack-contrib/storybook-rsbuild/issues/59.
Fortunately, I supported overwriting configuration through callback functions at that time. 🥹

fix: prevent merging the default option of rsbuild-plugin-html-minifier-terser

---

packages/builder-rsbuild/package.json
packages/react-rsbuild/package.json
packages/vue3-rsbuild/package.json

When 1.x released, it should meets the peer dep requirements.

fix: peer dep compat with 1.x version

---

packages/builder-rsbuild/src/preview/iframe-rsbuild.config.ts

Fix #70.
Should strip extra leading slash in dev mode, I guess the existing slash is introduced by Storybook.

fix: asset paths in dev mode

---

README.md
packages/builder-rsbuild/src/preview/iframe-rsbuild.config.ts
packages/builder-rsbuild/src/types.ts

Allow passing @storybook/addon-docs options via framework options

---

packages/builder-rsbuild/package.json
packages/builder-rsbuild/src/preview/virtual-module-mapping.ts
pnpm-lock.yaml

Add support for customizing the cache directory using the `CACHE_DIR` environment variable via https://www.npmjs.com/package/find-cache-dir.
Resolves: https://github.com/rspack-contrib/storybook-rsbuild/issues/197

feat(builder): use find-cache-dir to support customizing cache directory location

---

packages/addon-rslib/package.json

because currently addon doesn't work because the defined `cjs` file doesn't exist in dist
Error when running Storybook
```sh
> storybook dev -p 6006
@storybook/core v8.4.7
WARN Could not resolve addon "storybook-addon-rslib", skipping. Is it installed?
```

fix(storybook-addon-rslib): use correct file extensions in `exports` object in package.json

---

packages/framework-react/src/plugins/react-docgen.ts

Fix https://github.com/rspack-contrib/storybook-rsbuild/issues/199.

fix(framework-react): do not hang when react-docgen-typescript throw

---

packages/builder-rsbuild/src/index.ts
website/docs/guide/faq.mdx

Call `afterListen` hook to trigger config inspection.

feat: support config debug in dev mode

---

packages/addon-rslib/package.json
pnpm-lock.yaml
sandboxes/rslib-react-component/package.json
sandboxes/rslib-react-mf/package.json
sandboxes/rslib-react-mf/rslib.config.ts

Close #217.
- The mf command has changed to `rslib mf-dev` from `rslib mf dev`
- The `server.port` must be defined in the root config node, instead of in lib config.

chore(sandbox): correct mf config

---

packages/builder-rsbuild/src/index.ts

Fix https://github.com/rspack-contrib/storybook-rsbuild/issues/243.
`resolveAddonName` accepts `configDir` argument of `string` type, `configDir` should be directly taken from `options`.
Previously, the `options` variable was shadowed in the function.

fix(builder): configDir should be not be undefined

---

packages/builder-rsbuild/src/preview/iframe-rsbuild.config.ts

Fix #250.
Previously, the final `resolve.extensions` will be forced overwritten to the built-in. It should be merged with user's customized config.

fix(builder): should merge with user’s resolve.extensions

---

packages/builder-rsbuild/src/index.ts

Close https://github.com/rspack-contrib/storybook-rsbuild/issues/254.
Avoid the warning threw from https://github.com/web-infra-dev/rsbuild/blob/8dc35dc1d1500d2f119875d46b6a07e27986d532/packages/core/src/provider/rspackConfig.ts#L167. It should not break anything.
`devServer` field is not supposed to work no matter before or after the PR.

fix(builder): clear `devServer` field validation warning

---

CDVC.mts
packages/addon-modernjs/package.json
packages/addon-modernjs/src/preset.ts
pnpm-lock.yaml
sandboxes/modernjs-react-mf/host/package.json
sandboxes/modernjs-react-mf/remote/package.json
sandboxes/modernjs-react/package.json
sandboxes/rslib-react-mf/package.json

- Downgrade `find-up` to ^5 as ^7 is pure ESM, and the addon will be bundled to CJS output, so downgrade is the only way without using `import()`.
- Unify dep version.

fix: unify deps

---

README.md
packages/builder-rsbuild/src/preview/iframe-rsbuild.config.ts

port https://github.com/storybookjs/storybook/blob/ce3915727c3a42d6107953b6b65f6008d704dd3d/code/builders/builder-webpack5/src/preview/iframe-webpack.config.ts#L209.

feat: support config.module.parser.javascript.unknownContextCritical
